### ISSUE TITLE
Error: Metal error no metal implementation for softmax-last-dim

### ISSUE THREAD

**Issue by bm777** [huggingface/candle#1613]
Cargo run error while running Phi-2 model in Macbook Pro M2.

```bash
cargo run
```

Error ->

```bash
Error: Metal error no metal implementation for softmax-last-dim
Caused by:
    no metal implementation for softmax-last-dim
```

.toml file:

```toml
# other dep
accelerate-src = { version = "0.3.2" }
candle-core = { git = "https://github.com/huggingface/candle.git", version = "0.3.0", features = ["metal"] }
```

There is no implementation for this, or I should use a specific branch for metal?

---------
And when using accelerate, I'm getting this:
```bash
Running on CPU, to run on GPU(metal), build this example with `--features metal`
```
