### ISSUE TITLE
Compilation in CLI Tests with Candle?

### ISSUE THREAD

**Issue by zachcp** [huggingface/candle#2657]
I am writing a series of tests on the CLI using the `assert_bin` crate.  When I run the tests they don't seem to use Cargo to detect my cargo system and the non-optimal compilation leads to really slow tests. For example, this directive works great for most test but not for CLI tests where the binary will be compiled and invoked separately.

```toml
[target.'cfg(target_os = "macos")'.features]
default = ["metal"]
```

Does anyone have a decent CLI testing setup either with this crate or another?

**Comment by zachcp** [comment]
This plus `cargo test --features metal` works well.

```toml
[package]
name = "ferritin-featurizers"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description.workspace = true

[features]
metal = [
    "candle-core/metal",
    "candle-nn/metal",
    "candle-transformers/metal",
    "candle-metal-kernels",
]

[dependencies]
anyhow.workspace = true
candle-core = { git = "https://github.com/huggingface/candle.git", package = "candle-core", features = [
] }
candle-hf-hub = "0.3.3"
candle-nn = { git = "https://github.com/huggingface/candle.git", package = "candle-nn" }
candle-transformers = { git = "https://github.com/huggingface/candle.git", package = "candle-transformers" }
clap = "4.5.21"
ferritin-core = { path = "../ferritin-core" }
ferritin-test-data = { path = "../ferritin-test-data" }
itertools.workspace = true
pdbtbx.workspace = true
rand = "0.8.5"
safetensors = "0.4.5"
strum = { version = "0.26", features = ["derive"] }
tokenizers = "0.21.0"

[target.'cfg(target_os = "macos")'.features]
metal = []

# Conditionally include Metal-related dependencies for macOS
[target.'cfg(target_os = "macos")'.dependencies]
candle-metal-kernels = { git = "https://github.com/huggingface/candle.git", package = "candle-metal-kernels", optional = true }


[dev-dependencies]
candle-examples = { git = "https://github.com/huggingface/candle.git", package = "candle-examples" }
ferritin-test-data = { path = "../ferritin-test-data" }
assert_cmd = "2.0.16"
tempfile = "3.14.0"

```
